[build]
  publish = "_site"
  command = "npm run build"

[[redirects]]
  from = "/.well-known/webfinger"
  to = "https://fosstodon.org/.well-known/webfinger?resource=acct:mattdecamp@fosstodon.org"
  status = 200